import { useEffect, useMemo, useState } from 'react';
import { Globe } from 'lucide-react';
import { useTranslation } from 'react-i18next';
import { invoke } from '@tauri-apps/api/core';
import { save as saveDialog, open as openDialog } from '@tauri-apps/plugin-dialog';
import { toast } from 'react-toastify';
import { useShallow } from 'zustand/react/shallow';
import ModuleShell from './ModuleShell';
import { useLibraryStore } from '../../store/useLibraryStore';
import { useProcessStore } from '../../store/useProcessStore';
import { ImageFile, Invokes } from '../ui/AppProperties';

interface Props {
  onBackToLibrary(): void;
}

function escapeHtml(s: string) {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildGalleryHtml(opts: {
  title: string;
  template: 'classic' | 'grid' | 'mosaic';
  cols: number;
  items: { name: string; src: string | null }[];
}): string {
  const { title, template, cols, items } = opts;
  const colClass =
    template === 'classic' ? 2 : template === 'mosaic' ? 4 : Math.min(5, Math.max(2, cols));
  const cells = items
    .map((it, i) => {
      const tall = template === 'mosaic' && i % 5 === 0;
      const img = it.src
        ? `<img src="${it.src}" alt="${escapeHtml(it.name)}" loading="lazy" data-full="${it.src}" />`
        : `<div class="ph">${escapeHtml(it.name)}</div>`;
      return `<figure class="cell${tall ? ' tall' : ''}" data-idx="${i}" data-name="${escapeHtml(
        it.name,
      )}" tabindex="0" role="button">${img}<figcaption>${escapeHtml(
        it.name,
      )}</figcaption></figure>`;
    })
    .join('\n');

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<title>${escapeHtml(title)}</title>
<style>
  :root { color-scheme: dark; }
  * { box-sizing: border-box; }
  body { margin: 0; font-family: system-ui, -apple-system, Segoe UI, sans-serif; background: #0d0d0d; color: #eee; }
  header { padding: 1.25rem 1.5rem 0.5rem; }
  h1 { margin: 0; font-size: 1.35rem; font-weight: 600; letter-spacing: 0.02em; }
  .meta { color: #888; font-size: 0.8rem; margin-top: 0.35rem; }
  .grid { display: grid; gap: 0.6rem; padding: 1rem 1.5rem 2rem; grid-template-columns: repeat(${colClass}, minmax(0, 1fr)); }
  .cell { margin: 0; background: #1a1a1a; border: 1px solid #2a2a2a; border-radius: 6px; overflow: hidden; aspect-ratio: 1; display: flex; flex-direction: column; }
  .cell.tall { grid-row: span 2; aspect-ratio: auto; min-height: 100%; }
  .cell img { width: 100%; height: 100%; object-fit: cover; flex: 1; }
  .cell .ph { flex: 1; display: flex; align-items: center; justify-content: center; color: #555; font-size: 0.75rem; padding: 0.5rem; text-align: center; }
  figcaption { font-size: 0.7rem; color: #999; padding: 0.35rem 0.5rem; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; border-top: 1px solid #2a2a2a; }
  footer { padding: 0 1.5rem 1.5rem; color: #555; font-size: 0.7rem; }
  .cell { cursor: zoom-in; }
  .cell:focus-within { outline: 1px solid #6af; }
  #lb { display: none; position: fixed; inset: 0; background: rgba(0,0,0,.92); z-index: 50; align-items: center; justify-content: center; flex-direction: column; gap: .75rem; padding: 1rem; }
  #lb.open { display: flex; }
  #lb img { max-width: min(96vw, 1400px); max-height: 82vh; object-fit: contain; border-radius: 4px; box-shadow: 0 8px 40px rgba(0,0,0,.6); }
  #lb .cap { color: #ccc; font-size: .85rem; max-width: 90vw; text-align: center; }
  #lb .hint { color: #666; font-size: .7rem; }
  #lb button { position: absolute; top: 1rem; right: 1rem; background: #222; color: #eee; border: 1px solid #444; border-radius: 6px; padding: .4rem .7rem; cursor: pointer; }
</style>
</head>
<body>
<header>
  <h1>${escapeHtml(title)}</h1>
  <div class="meta">${items.length} photo${items.length === 1 ? '' : 's'} · ${escapeHtml(template)} layout · exported from RustROOM</div>
</header>
<main class="grid">
${cells}
</main>
<footer>Generated by RustROOM Web module (public LR-style layout). Thumbnails embedded when available. Click a photo for lightbox · Esc / ← → navigate.</footer>
<div id="lb" aria-hidden="true">
  <button type="button" id="lb-close" aria-label="Close">Close</button>
  <img id="lb-img" alt="" />
  <div class="cap" id="lb-cap"></div>
  <div class="hint">Esc close · ← → previous/next · click backdrop to close</div>
</div>
<script>
(function(){
  var slides = ${JSON.stringify(
    items.map((it) => ({ name: it.name, src: it.src })),
  )};
  var lb = document.getElementById('lb');
  var img = document.getElementById('lb-img');
  var cap = document.getElementById('lb-cap');
  var closeBtn = document.getElementById('lb-close');
  var i = 0;
  function show(n){
    if(!slides.length) return;
    i = (n + slides.length) % slides.length;
    var s = slides[i];
    if(s.src){ img.src = s.src; img.style.display = ''; }
    else { img.removeAttribute('src'); img.style.display = 'none'; }
    cap.textContent = (i+1) + ' / ' + slides.length + ' · ' + (s.name || '');
    lb.classList.add('open');
    lb.setAttribute('aria-hidden','false');
  }
  function hide(){ lb.classList.remove('open'); lb.setAttribute('aria-hidden','true'); }
  document.querySelectorAll('.cell').forEach(function(el){
    el.addEventListener('click', function(){ show(parseInt(el.getAttribute('data-idx')||'0',10)); });
    el.addEventListener('keydown', function(e){ if(e.key==='Enter'||e.key===' '){ e.preventDefault(); show(parseInt(el.getAttribute('data-idx')||'0',10)); }});
  });
  closeBtn.onclick = hide;
  lb.addEventListener('click', function(e){ if(e.target===lb) hide(); });
  document.addEventListener('keydown', function(e){
    if(!lb.classList.contains('open')) return;
    if(e.key==='Escape') hide();
    if(e.key==='ArrowRight') show(i+1);
    if(e.key==='ArrowLeft') show(i-1);
  });
})();
</script>
</body>
</html>
`;
}

/**
 * Lightroom Classic–style Web gallery module with live preview + HTML export.
 */
export default function WebModuleView({ onBackToLibrary }: Props) {
  const { t } = useTranslation();
  const [template, setTemplate] = useState<'classic' | 'grid' | 'mosaic'>('grid');
  const [title, setTitle] = useState('Photo Gallery');
  const [cols, setCols] = useState(3);
  const [exporting, setExporting] = useState(false);
  const [lastExportPath, setLastExportPath] = useState<string | null>(null);

  const { imageList, multiSelectedPaths } = useLibraryStore(
    useShallow((s) => ({
      imageList: s.imageList,
      multiSelectedPaths: s.multiSelectedPaths,
    })),
  );
  const thumbs = useProcessStore((s) => s.thumbnails);

  const photos = useMemo(() => {
    const paths =
      multiSelectedPaths.length > 0
        ? multiSelectedPaths
        : imageList.slice(0, 24).map((i: ImageFile) => i.path);
    return paths
      .map((p) => imageList.find((i: ImageFile) => i.path === p))
      .filter(Boolean) as ImageFile[];
  }, [multiSelectedPaths, imageList]);

  useEffect(() => {
    const paths = photos.map((p) => p.path);
    if (paths.length) invoke('update_thumbnail_queue', { paths }).catch(() => {});
  }, [photos]);

  const handleExportHtml = async () => {
    if (photos.length === 0) {
      toast.info(t('ui.web.empty' as any, { defaultValue: 'Select photos in Library' }));
      return;
    }
    setExporting(true);
    try {
      const safeTitle = (title || 'gallery').replace(/[^\w\-]+/g, '_').slice(0, 60) || 'gallery';
      const filePath = await saveDialog({
        defaultPath: `${safeTitle}.html`,
        filters: [{ name: 'HTML', extensions: ['html', 'htm'] }],
        title: t('ui.web.exportHtml' as any, { defaultValue: 'Export HTML' }),
      });
      if (!filePath) return;

      const items = photos.map((img) => {
        const name = img.path.split(/[\\/]/).pop()?.split('?')[0] || img.path;
        const src = thumbs[img.path] || null;
        // Only embed data URLs / http(s); skip blob: (not portable on disk)
        const portable =
          src && (src.startsWith('data:') || src.startsWith('http://') || src.startsWith('https://'))
            ? src
            : null;
        return { name, src: portable };
      });

      const html = buildGalleryHtml({ title, template, cols, items });
      await invoke(Invokes.WriteTextFile, { path: filePath, contents: html });
      setLastExportPath(filePath);
      toast.success(
        t('ui.web.exportDone' as any, {
          defaultValue: 'Gallery HTML saved ({{count}} photos)',
          count: photos.length,
        }),
      );
    } catch (e) {
      toast.error(String(e));
    } finally {
      setExporting(false);
    }
  };

  /** Multi-file package: folder/index.html + images/* (LR-style web gallery package). */
  const handleExportPackage = async () => {
    if (photos.length === 0) {
      toast.info(t('ui.web.empty' as any, { defaultValue: 'Select photos in Library' }));
      return;
    }
    setExporting(true);
    try {
      const safeTitle = (title || 'gallery').replace(/[^\w\-]+/g, '_').slice(0, 60) || 'gallery';
      const parentDir = await openDialog({
        directory: true,
        multiple: false,
        title: t('ui.web.exportPackagePick' as any, {
          defaultValue: 'Choose folder for web gallery package',
        }),
      });
      if (!parentDir || typeof parentDir !== 'string') return;

      const packageRoot = `${parentDir.replace(/[\\/]+$/, '')}/${safeTitle}`;
      const imagesDir = `${packageRoot}/images`;
      await invoke(Invokes.CreateFolder, { path: imagesDir });

      // Build unique disk names for selection collisions
      const used = new Map<string, number>();
      const plan: { name: string; sourcePath: string; diskName: string }[] = [];
      for (const img of photos) {
        const base = img.path.split(/[\\/]/).pop()?.split('?')[0] || 'photo.jpg';
        const lower = base.toLowerCase();
        let diskName = base;
        if (used.has(lower)) {
          const n = (used.get(lower) || 1) + 1;
          used.set(lower, n);
          const dot = base.lastIndexOf('.');
          const stem = dot > 0 ? base.slice(0, dot) : base;
          const ext = dot > 0 ? base.slice(dot) : '';
          diskName = `${stem}_${n}${ext}`;
        } else {
          used.set(lower, 1);
        }
        plan.push({ name: base, sourcePath: img.path, diskName });
      }

      // Copy each file with unique disk name (handles basename collisions)
      for (const item of plan) {
        await invoke(Invokes.CopyFileTo, {
          sourcePath: item.sourcePath,
          destinationPath: `${imagesDir}/${item.diskName}`,
        });
      }

      const hasCollision = plan.some((p) => p.diskName !== p.name);

      const htmlItems = plan.map((p) => ({
        name: p.name,
        src: `images/${p.diskName}`,
      }));

      const html = buildGalleryHtml({ title, template, cols, items: htmlItems });
      const indexPath = `${packageRoot}/index.html`;
      await invoke(Invokes.WriteTextFile, { path: indexPath, contents: html });
      setLastExportPath(packageRoot);
      toast.success(
        t('ui.web.exportPackageDone' as any, {
          defaultValue: hasCollision
            ? 'Gallery package saved ({{count}} photos; unique names for collisions)'
            : 'Gallery package saved ({{count}} photos + index.html)',
          count: photos.length,
        }),
      );
    } catch (e) {
      toast.error(String(e));
    } finally {
      setExporting(false);
    }
  };


  return (
    <ModuleShell
      moduleId="web"
      title={t('ui.moduleBar.web' as any)}
      subtitle={t('ui.moduleShell.webSubtitle' as any, {
        defaultValue: 'Web gallery preview and HTML export from the current selection.',
      })}
      icon={Globe}
      onBackToLibrary={onBackToLibrary}
      left={
        <>
          <div className="px-2 py-1 text-[10px] uppercase tracking-wider text-white/35">
            {t('ui.web.templates' as any, { defaultValue: 'Template browser' })}
          </div>
          {(
            [
              ['classic', 'Classic'],
              ['grid', 'Grid'],
              ['mosaic', 'Mosaic'],
            ] as const
          ).map(([id, label]) => (
            <button
              key={id}
              type="button"
              onClick={() => setTemplate(id)}
              className={`w-full text-left px-2 py-1.5 rounded text-[12px] ${
                template === id ? 'bg-white/10 text-white' : 'text-white/70 hover:bg-white/5'
              }`}
            >
              {label}
            </button>
          ))}
        </>
      }
      right={
        <>
          <section className="space-y-2">
            <div className="text-[10px] uppercase tracking-wider text-white/35">
              {t('ui.web.siteInfo' as any, { defaultValue: 'Site info' })}
            </div>
            <label className="block text-[11px] text-white/60">
              {t('ui.web.title' as any, { defaultValue: 'Title' })}
              <input
                className="mt-1 w-full h-8 rounded bg-white/5 border border-white/10 px-2 text-white/90"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </label>
            {template === 'grid' && (
              <label className="block text-[11px] text-white/60">
                {t('ui.web.columns' as any, { defaultValue: 'Columns' })}
                <input
                  type="range"
                  min={2}
                  max={5}
                  value={cols}
                  onChange={(e) => setCols(Number(e.target.value))}
                  className="mt-1 w-full"
                />
              </label>
            )}
            <div className="text-[10px] uppercase tracking-wider text-white/35 mt-2">
              {t('ui.web.output' as any, { defaultValue: 'Output' })}
            </div>
            <button
              type="button"
              disabled={exporting || photos.length === 0}
              onClick={handleExportHtml}
              className="w-full h-8 rounded bg-white/15 hover:bg-white/25 disabled:opacity-40 disabled:cursor-not-allowed text-[11px] text-white font-semibold uppercase tracking-wide"
            >
              {exporting
                ? t('ui.web.exporting' as any, { defaultValue: 'Exporting…' })
                : t('ui.web.exportHtml' as any, { defaultValue: 'Export HTML' })}
            </button>
            <button
              type="button"
              disabled={exporting || photos.length === 0}
              onClick={handleExportPackage}
              className="w-full h-8 rounded bg-accent/80 hover:bg-accent disabled:opacity-40 disabled:cursor-not-allowed text-[11px] text-button-text font-semibold uppercase tracking-wide"
              data-tooltip={t('ui.web.exportPackageTip' as any, {
                defaultValue: 'Folder with images/ + index.html (portable multi-file package)',
              })}
            >
              {exporting
                ? t('ui.web.exporting' as any, { defaultValue: 'Exporting…' })
                : t('ui.web.exportPackage' as any, { defaultValue: 'Export package…' })}
            </button>
            {lastExportPath && (
              <button
                type="button"
                className="w-full h-8 rounded border border-white/15 text-[12px] text-white/75 hover:bg-white/5"
                onClick={() => {
                  invoke(Invokes.ShowInFinder, { path: lastExportPath }).catch(() => {});
                }}
              >
                {t('ui.web.showInFolder' as any, { defaultValue: 'Show in folder' })}
              </button>
            )}
            <p className="text-[10px] text-white/35 leading-relaxed">
              {t('ui.web.note' as any, {
                defaultValue:
                  'HTML: single file (embedded thumbs when available). Package: folder with images/ + index.html for sharing.',
              })}
            </p>
          </section>
        </>
      }
    >
      <div className="w-full h-full min-h-[280px] rounded border border-white/10 bg-[#0d0d0d] overflow-auto p-4">
        <h2 className="text-white/90 text-[16px] font-semibold mb-3 tracking-wide">{title}</h2>
        <div
          className={`grid gap-2 ${
            template === 'classic'
              ? 'grid-cols-2'
              : template === 'mosaic'
                ? 'grid-cols-4 auto-rows-[80px]'
                : cols === 2
                  ? 'grid-cols-2'
                  : cols === 3
                    ? 'grid-cols-3'
                    : cols === 4
                      ? 'grid-cols-4'
                      : 'grid-cols-5'
          }`}
        >
          {photos.length === 0 ? (
            <div className="col-span-full text-center text-white/30 text-[12px] py-16 uppercase tracking-widest">
              {t('ui.web.empty' as any, { defaultValue: 'Select photos in Library' })}
            </div>
          ) : (
            photos.map((img, i) => {
              const src = thumbs[img.path];
              const tall = template === 'mosaic' && i % 5 === 0;
              return (
                <div
                  key={img.path}
                  className={`rounded overflow-hidden bg-white/5 border border-white/10 ${
                    tall ? 'row-span-2' : ''
                  } aspect-square`}
                >
                  {src ? (
                    <img src={src} alt="" className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full animate-pulse bg-white/5" />
                  )}
                </div>
              );
            })
          )}
        </div>
      </div>
    </ModuleShell>
  );
}
