//! Backend performance benchmark (test-only, never compiled into the app).
//!
//! Run with:
//!   cd src-tauri && cargo test --lib perf_bench -- --ignored --nocapture --test-threads=1
//!
//! Env vars:
//!   RUSTROOM_BENCH_DIR   input folder (default: the eclipse RAW folder on the external SSD)
//!   RUSTROOM_BENCH_REPS  timed repetitions per measurement (default 3, plus 1 warmup)
//!   RUSTROOM_BENCH_ARWS  number of ARW files to sample (default 5)
//!
//! Results are printed and written to <repo>/bench/out/backend_bench.md.
//! Everything here calls the real production functions; where a production entry
//! point needs a Tauri AppHandle/State, the handle-free core is replicated and
//! noted in the table.

use std::borrow::Cow;
use std::collections::HashMap;
use std::fs;
use std::io::Read;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use half::f16;
use image::{DynamicImage, GenericImageView, ImageBuffer, Rgba};
use rawler::decoders::RawDecodeParams;
use rawler::imgop::develop::{DemosaicAlgorithm, Intermediate, ProcessingStep, RawDevelop};
use rawler::imgop::sensor::bayer::{Demosaic, ppg::PPGDemosaic};
use rawler::pixarray::PixF32;
use rawler::rawimage::{RawImage, RawPhotometricInterpretation};
use rawler::rawsource::RawSource;
use rayon::prelude::*;
use wgpu::util::{DeviceExt, TextureDataOrder};

use crate::app_settings::AppSettings;
use crate::file_management::{bench_hooks, parse_virtual_path, read_file_mapped};
use crate::gpu_processing::{GpuProcessor, RenderRequest, Roi};
use crate::image_processing::{
    GpuContext, ImageMetadata, apply_coarse_rotation, apply_geometry_warp,
    calculate_histogram_from_image, calculate_waveform_from_image, downscale_f32_image,
    get_all_adjustments_from_json, is_image_edited, remove_raw_artifacts_and_enhance,
    resolve_tonemapper_override,
};

const DEFAULT_DIR: &str = "/Volumes/Extreme SSD/PHOTOGRAPHIE_VIDEOS/2026_08_12_ECLIPSE_SOLAIRE/RAW";

// ---------------------------------------------------------------------------
// Timing / reporting helpers
// ---------------------------------------------------------------------------

struct Row {
    section: String,
    stage: String,
    samples: Vec<f64>,
    note: String,
}

#[derive(Default)]
struct Report {
    rows: Vec<Row>,
    info: Vec<String>,
    section: String,
}

impl Report {
    fn section(&mut self, s: &str) {
        self.section = s.to_string();
        println!("\n=== {} ===", s);
    }

    fn add(&mut self, stage: &str, samples: Vec<f64>, note: &str) {
        if samples.is_empty() {
            return;
        }
        let (med, min, max) = stats(&samples);
        println!(
            "  {:<58} n={:<3} med={:>9.2} ms  min={:>9.2}  max={:>9.2}  {}",
            stage,
            samples.len(),
            med,
            min,
            max,
            note
        );
        self.rows.push(Row {
            section: self.section.clone(),
            stage: stage.to_string(),
            samples,
            note: note.to_string(),
        });
    }

    /// Merge samples into an existing row with the same stage name (per-file accumulation).
    fn acc(&mut self, stage: &str, samples: Vec<f64>, note: &str) {
        if let Some(r) = self
            .rows
            .iter_mut()
            .find(|r| r.stage == stage && r.section == self.section)
        {
            r.samples.extend(samples);
        } else {
            self.rows.push(Row {
                section: self.section.clone(),
                stage: stage.to_string(),
                samples,
                note: note.to_string(),
            });
        }
    }

    fn info(&mut self, s: String) {
        println!("  [info] {}", s);
        self.info.push(s);
    }

    fn to_markdown(&self) -> String {
        let mut out = String::new();
        out.push_str("# RustROOM backend benchmark\n\n");
        out.push_str("Generated by `cargo test --lib perf_bench -- --ignored --nocapture --test-threads=1` (src-tauri/src/perf_bench.rs).\n");
        out.push_str("All times in milliseconds; median / min / max over timed repetitions (1 warmup discarded), pooled across the sampled files.\n\n");
        out.push_str("## Environment\n\n");
        for i in &self.info {
            out.push_str(&format!("- {}\n", i));
        }
        let mut current = String::new();
        for r in &self.rows {
            if r.section != current {
                current = r.section.clone();
                out.push_str(&format!(
                    "\n## {}\n\n| Stage | n | median | min | max | notes |\n|---|---:|---:|---:|---:|---|\n",
                    current
                ));
            }
            let (med, min, max) = stats(&r.samples);
            out.push_str(&format!(
                "| {} | {} | {:.2} | {:.2} | {:.2} | {} |\n",
                r.stage,
                r.samples.len(),
                med,
                min,
                max,
                r.note
            ));
        }
        out
    }

    fn print_final_table(&self) {
        println!("\n\n================ FINAL TABLE (ms) ================");
        let mut current = String::new();
        for r in &self.rows {
            if r.section != current {
                current = r.section.clone();
                println!("\n-- {} --", current);
                println!(
                    "{:<62} {:>4} {:>10} {:>10} {:>10}",
                    "stage", "n", "median", "min", "max"
                );
            }
            let (med, min, max) = stats(&r.samples);
            println!(
                "{:<62} {:>4} {:>10.2} {:>10.2} {:>10.2}",
                r.stage,
                r.samples.len(),
                med,
                min,
                max
            );
        }
    }
}

fn stats(samples: &[f64]) -> (f64, f64, f64) {
    let mut s = samples.to_vec();
    s.sort_by(|a, b| a.partial_cmp(b).unwrap());
    let n = s.len();
    let med = if n % 2 == 1 {
        s[n / 2]
    } else {
        (s[n / 2 - 1] + s[n / 2]) / 2.0
    };
    (med, s[0], s[n - 1])
}

fn ms(d: Duration) -> f64 {
    d.as_secs_f64() * 1000.0
}

/// 1 warmup + `reps` timed calls. Returns (samples_ms, last result).
/// The previous result is dropped *before* the timer starts, so large outputs
/// (500 MB images) never coexist and their deallocation is not timed.
fn bench<T>(reps: usize, mut f: impl FnMut() -> T) -> (Vec<f64>, T) {
    let mut last = Some(f());
    let mut samples = Vec::with_capacity(reps);
    for _ in 0..reps {
        drop(last.take());
        let t = Instant::now();
        let r = f();
        samples.push(ms(t.elapsed()));
        last = Some(r);
    }
    (samples, last.unwrap())
}

fn env_usize(key: &str, default: usize) -> usize {
    std::env::var(key)
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(default)
}

fn pick_spread<T: Clone>(items: &[T], k: usize) -> Vec<T> {
    if items.is_empty() || k == 0 {
        return Vec::new();
    }
    if k == 1 {
        return vec![items[items.len() / 2].clone()];
    }
    let n = items.len();
    (0..k.min(n))
        .map(|i| items[i * (n - 1) / (k.min(n) - 1)].clone())
        .collect()
}

fn load_user_settings() -> (AppSettings, String) {
    let home = std::env::var("HOME").unwrap_or_default();
    let p = PathBuf::from(home)
        .join("Library/Application Support/io.github.CyberTimon.RapidRAW/settings.json");
    if let Ok(s) = fs::read_to_string(&p)
        && let Ok(settings) = serde_json::from_str::<AppSettings>(&s)
    {
        return (settings, format!("user settings from {}", p.display()));
    }
    (AppSettings::default(), "AppSettings::default()".to_string())
}

// ---------------------------------------------------------------------------
// GPU helpers (headless replica of get_or_init_gpu_context, no surface)
// ---------------------------------------------------------------------------

fn make_headless_gpu_context() -> Option<(GpuContext, String)> {
    let instance_desc = wgpu::InstanceDescriptor::new_without_display_handle_from_env();
    let instance = wgpu::Instance::new(instance_desc);
    let adapter = pollster::block_on(instance.request_adapter(&wgpu::RequestAdapterOptions {
        power_preference: wgpu::PowerPreference::HighPerformance,
        compatible_surface: None,
        ..Default::default()
    }))
    .ok()?;
    let info = adapter.get_info();
    let mut required_features = wgpu::Features::empty();
    if adapter
        .features()
        .contains(wgpu::Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES)
    {
        required_features |= wgpu::Features::TEXTURE_ADAPTER_SPECIFIC_FORMAT_FEATURES;
    }
    let limits = adapter.limits();
    let (device, queue) = pollster::block_on(adapter.request_device(&wgpu::DeviceDescriptor {
        label: Some("Processing Device (bench)"),
        required_features,
        required_limits: limits.clone(),
        experimental_features: wgpu::ExperimentalFeatures::default(),
        memory_hints: wgpu::MemoryHints::Performance,
        trace: wgpu::Trace::Off,
    }))
    .ok()?;
    Some((
        GpuContext {
            device: Arc::new(device),
            queue: Arc::new(queue),
            limits,
            display: Arc::new(Mutex::new(None)),
        },
        format!("{} ({:?}, {:?})", info.name, info.backend, info.device_type),
    ))
}

fn gpu_wait(ctx: &GpuContext) {
    let _ = ctx.device.poll(wgpu::PollType::Wait {
        submission_index: None,
        timeout: Some(Duration::from_secs(60)),
    });
}

/// Same as gpu_processing::to_rgba_f16 (private there).
fn to_rgba_f16(img: &DynamicImage) -> Vec<f16> {
    let rgba_f32 = img.to_rgba32f();
    rgba_f32.into_raw().into_iter().map(f16::from_f32).collect()
}

/// Same texture creation as process_and_get_dynamic_image_inner (cache miss path).
fn create_input_texture(
    ctx: &GpuContext,
    data: &[f16],
    width: u32,
    height: u32,
) -> (wgpu::Texture, wgpu::TextureView) {
    let texture = ctx.device.create_texture_with_data(
        &ctx.queue,
        &wgpu::TextureDescriptor {
            label: Some("Input Texture"),
            size: wgpu::Extent3d {
                width,
                height,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba16Float,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
            view_formats: &[],
        },
        TextureDataOrder::MipMajor,
        bytemuck::cast_slice(data),
    );
    let view = texture.create_view(&Default::default());
    (texture, view)
}

fn padded(v: u32) -> u32 {
    (v + 255) & !255
}

/// Readback path: processor.run(skip_readback=false, display=false) -> RGBA8 image.
fn render_readback(
    p: &GpuProcessor,
    view: &wgpu::TextureView,
    w: u32,
    h: u32,
    adj: &serde_json::Value,
    tm: Option<u32>,
    roi: Option<Roi>,
) -> DynamicImage {
    let (px, ow, oh, _, _) = p
        .run(
            view,
            w,
            h,
            RenderRequest {
                adjustments: get_all_adjustments_from_json(adj, true, tm),
                mask_bitmaps: &[],
                lut: None,
                roi,
            },
            false,
            false,
        )
        .expect("gpu run failed");
    DynamicImage::ImageRgba8(ImageBuffer::<Rgba<u8>, _>::from_raw(ow, oh, px).unwrap())
}

/// Display path (use_wgpu_renderer = true): run(skip_readback, output_to_display),
/// copy working->output like process_and_get_dynamic_image_inner, then wait for the GPU
/// (the app polls with a 500ms timeout right after, before emitting wgpu-frame-ready).
/// Surface present is not included (no window).
fn render_display(
    ctx: &GpuContext,
    p: &GpuProcessor,
    view: &wgpu::TextureView,
    w: u32,
    h: u32,
    adj: &serde_json::Value,
    tm: Option<u32>,
    roi: Option<Roi>,
) {
    let (_, out_w, out_h, out_x, out_y) = p
        .run(
            view,
            w,
            h,
            RenderRequest {
                adjustments: get_all_adjustments_from_json(adj, true, tm),
                mask_bitmaps: &[],
                lut: None,
                roi,
            },
            true,
            true,
        )
        .expect("gpu run failed");
    let mut enc = ctx
        .device
        .create_command_encoder(&wgpu::CommandEncoderDescriptor { label: None });
    let origin = wgpu::Origin3d {
        x: out_x,
        y: out_y,
        z: 0,
    };
    enc.copy_texture_to_texture(
        wgpu::TexelCopyTextureInfo {
            texture: &p.working_texture,
            mip_level: 0,
            origin,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::TexelCopyTextureInfo {
            texture: &p.output_texture,
            mip_level: 0,
            origin,
            aspect: wgpu::TextureAspect::All,
        },
        wgpu::Extent3d {
            width: out_w,
            height: out_h,
            depth_or_array_layers: 1,
        },
    );
    ctx.queue.submit(Some(enc.finish()));
    gpu_wait(ctx);
}

/// Standalone replica of GpuProcessor's separable blur passes (same blur.wgsl, same
/// bind layout, same dispatch sizes, one submit per blur) to isolate their GPU cost.
#[repr(C)]
#[derive(Debug, Copy, Clone, bytemuck::Pod, bytemuck::Zeroable)]
struct BenchBlurParams {
    radius: u32,
    tile_offset_x: u32,
    tile_offset_y: u32,
    input_width: u32,
    input_height: u32,
    _pad1: u32,
    _pad2: u32,
    _pad3: u32,
}

struct BlurBench {
    bgl: wgpu::BindGroupLayout,
    h: wgpu::ComputePipeline,
    v: wgpu::ComputePipeline,
    params: wgpu::Buffer,
    ping_view: wgpu::TextureView,
    out_view: wgpu::TextureView,
}

impl BlurBench {
    fn new(ctx: &GpuContext, tile_w: u32, tile_h: u32) -> Self {
        let device = &ctx.device;
        let module = device.create_shader_module(wgpu::ShaderModuleDescriptor {
            label: Some("bench blur"),
            source: wgpu::ShaderSource::Wgsl(include_str!("shaders/blur.wgsl").into()),
        });
        let bgl = device.create_bind_group_layout(&wgpu::BindGroupLayoutDescriptor {
            label: None,
            entries: &[
                wgpu::BindGroupLayoutEntry {
                    binding: 0,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Texture {
                        sample_type: wgpu::TextureSampleType::Float { filterable: false },
                        view_dimension: wgpu::TextureViewDimension::D2,
                        multisampled: false,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 1,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::StorageTexture {
                        access: wgpu::StorageTextureAccess::WriteOnly,
                        format: wgpu::TextureFormat::Rgba16Float,
                        view_dimension: wgpu::TextureViewDimension::D2,
                    },
                    count: None,
                },
                wgpu::BindGroupLayoutEntry {
                    binding: 2,
                    visibility: wgpu::ShaderStages::COMPUTE,
                    ty: wgpu::BindingType::Buffer {
                        ty: wgpu::BufferBindingType::Uniform,
                        has_dynamic_offset: false,
                        min_binding_size: None,
                    },
                    count: None,
                },
            ],
        });
        let layout = device.create_pipeline_layout(&wgpu::PipelineLayoutDescriptor {
            label: None,
            bind_group_layouts: &[Some(&bgl)],
            immediate_size: 0,
        });
        let mk = |entry: &str| {
            device.create_compute_pipeline(&wgpu::ComputePipelineDescriptor {
                label: None,
                layout: Some(&layout),
                module: &module,
                entry_point: Some(entry),
                compilation_options: Default::default(),
                cache: None,
            })
        };
        let h = mk("horizontal_blur");
        let v = mk("vertical_blur");
        let params = device.create_buffer(&wgpu::BufferDescriptor {
            label: None,
            size: std::mem::size_of::<BenchBlurParams>() as u64,
            usage: wgpu::BufferUsages::UNIFORM | wgpu::BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });
        let desc = wgpu::TextureDescriptor {
            label: None,
            size: wgpu::Extent3d {
                width: tile_w,
                height: tile_h,
                depth_or_array_layers: 1,
            },
            mip_level_count: 1,
            sample_count: 1,
            dimension: wgpu::TextureDimension::D2,
            format: wgpu::TextureFormat::Rgba16Float,
            usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::STORAGE_BINDING,
            view_formats: &[],
        };
        let ping_view = device.create_texture(&desc).create_view(&Default::default());
        let out_view = device.create_texture(&desc).create_view(&Default::default());
        Self {
            bgl,
            h,
            v,
            params,
            ping_view,
            out_view,
        }
    }

    /// One run_blur() call as in GpuProcessor::run (tile at offset x0,y0 of size iw x ih).
    fn run(
        &self,
        ctx: &GpuContext,
        input: &wgpu::TextureView,
        radius: u32,
        x0: u32,
        y0: u32,
        iw: u32,
        ih: u32,
    ) {
        let device = &ctx.device;
        ctx.queue.write_buffer(
            &self.params,
            0,
            bytemuck::bytes_of(&BenchBlurParams {
                radius,
                tile_offset_x: x0,
                tile_offset_y: y0,
                input_width: iw,
                input_height: ih,
                _pad1: 0,
                _pad2: 0,
                _pad3: 0,
            }),
        );
        let mut enc = device.create_command_encoder(&Default::default());
        let bg = |src: &wgpu::TextureView, dst: &wgpu::TextureView| {
            device.create_bind_group(&wgpu::BindGroupDescriptor {
                label: None,
                layout: &self.bgl,
                entries: &[
                    wgpu::BindGroupEntry {
                        binding: 0,
                        resource: wgpu::BindingResource::TextureView(src),
                    },
                    wgpu::BindGroupEntry {
                        binding: 1,
                        resource: wgpu::BindingResource::TextureView(dst),
                    },
                    wgpu::BindGroupEntry {
                        binding: 2,
                        resource: self.params.as_entire_binding(),
                    },
                ],
            })
        };
        let hbg = bg(input, &self.ping_view);
        {
            let mut c = enc.begin_compute_pass(&Default::default());
            c.set_pipeline(&self.h);
            c.set_bind_group(0, &hbg, &[]);
            c.dispatch_workgroups(iw.div_ceil(256), ih, 1);
        }
        let vbg = bg(&self.ping_view, &self.out_view);
        {
            let mut c = enc.begin_compute_pass(&Default::default());
            c.set_pipeline(&self.v);
            c.set_bind_group(0, &vbg, &[]);
            c.dispatch_workgroups(iw, ih.div_ceil(256), 1);
        }
        ctx.queue.submit(Some(enc.finish()));
    }
}

/// Times the 4 blurs GpuProcessor::run always executes for one tile.
/// scale = min(image_w, image_h)/1080 as in run(); radii = ceil(base*scale).
fn bench_blurs(
    rep: &mut Report,
    ctx: &GpuContext,
    bb: &BlurBench,
    input: &wgpu::TextureView,
    img_w: u32,
    img_h: u32,
    tile: (u32, u32, u32, u32),
    label: &str,
    reps: usize,
) {
    let scale = (img_w.min(img_h) as f32) / 1080.0;
    let (x0, y0, iw, ih) = tile;
    let mut total = Vec::new();
    for (name, base) in [
        ("sharpness r=1", 1.0f32),
        ("tonal r=3.5", 3.5),
        ("clarity r=8", 8.0),
        ("structure r=40", 40.0),
    ] {
        let radius = (base * scale).ceil().max(1.0) as u32;
        let (s, _) = bench(reps, || {
            bb.run(ctx, input, radius, x0, y0, iw, ih);
            gpu_wait(ctx);
        });
        rep.acc(
            &format!("  - {} blur {} (radius {}px, {} taps x2 passes)", label, name, radius, 2 * radius + 1),
            s,
            "h+v separable, gaussian exp() per tap",
        );
    }
    let (s, _) = bench(reps, || {
        for base in [1.0f32, 3.5, 8.0, 40.0] {
            let radius = (base * scale).ceil().max(1.0) as u32;
            bb.run(ctx, input, radius, x0, y0, iw, ih);
        }
        gpu_wait(ctx);
    });
    total.extend(s);
    rep.acc(
        &format!("  - {} all 4 blurs (one tile {}x{})", label, iw, ih),
        total,
        "always executed, independent of slider values",
    );
}

fn edit_adjustments(exposure: f64) -> serde_json::Value {
    serde_json::json!({
        "exposure": exposure,
        "contrast": 12.0,
        "highlights": -25.0,
        "shadows": 20.0,
        "whites": 5.0,
        "blacks": -5.0,
        "vibrance": 10.0,
        "saturation": 5.0,
        "clarity": 10.0,
        "sharpness": 20.0,
    })
}

// ---------------------------------------------------------------------------
// RAW helpers (replicas of raw_processing::develop_internal pieces, for breakdown)
// ---------------------------------------------------------------------------

/// Decode exactly like develop_internal's prelude.
fn decode_like_production(bytes: &[u8]) -> (RawImage, f32) {
    let source = RawSource::new_from_slice(bytes);
    let decoder = rawler::get_decoder(&source).expect("no decoder");
    let mut raw_image = decoder
        .raw_image(&source, &RawDecodeParams::default(), false)
        .expect("raw_image failed");
    let white = raw_image.whitelevel.0.first().cloned().unwrap_or(u16::MAX as u32) as f32;
    let black = raw_image.blacklevel.levels.first().map(|r| r.as_f32()).unwrap_or(0.0);
    let rescale_factor = (u32::MAX as f32 - black) / (white - black).max(1.0);
    for level in raw_image.whitelevel.0.iter_mut() {
        *level = u32::MAX;
    }
    raw_image.wb_coeffs =
        crate::multi_exposure::neutralize_wb_if_multiexposure(raw_image.wb_coeffs, bytes);
    (raw_image, rescale_factor)
}

fn production_developer(fast: bool) -> RawDevelop {
    let mut d = RawDevelop::default();
    if fast {
        d.demosaic_algorithm = DemosaicAlgorithm::Speed;
    }
    d.steps.retain(|&s| s != ProcessingStep::SRgb);
    d
}

#[inline]
fn bench_srgb_to_linear(value: f32) -> f32 {
    if value <= 0.04045 {
        value / 12.92
    } else {
        ((value + 0.055) / 1.055).powf(3.0)
    }
}

/// Verbatim copy of develop_internal's ThreeColor post-develop loop (raw_processing.rs),
/// including the runtime `is_linear_format && apply_ungamma` branch (false for Bayer ARW,
/// passed through black_box so it stays a runtime check exactly as in production).
fn post_rescale_highlight(inter: &mut Intermediate, rescale_factor: f32, hc: f32, fast: bool) {
    let is_linear_format = std::hint::black_box(false);
    let apply_ungamma = std::hint::black_box(false);
    let safe_highlight_compression = hc.max(1.01);
    let clamp_limit = if fast { 1.0 } else { safe_highlight_compression };
    if let Intermediate::ThreeColor(pixels) = inter {
        pixels.data.iter_mut().for_each(|p| {
            let mut r = (p[0] * rescale_factor).max(0.0);
            let mut g = (p[1] * rescale_factor).max(0.0);
            let mut b = (p[2] * rescale_factor).max(0.0);
            if is_linear_format && apply_ungamma {
                r = bench_srgb_to_linear(r.clamp(0.0, 1.0));
                g = bench_srgb_to_linear(g.clamp(0.0, 1.0));
                b = bench_srgb_to_linear(b.clamp(0.0, 1.0));
            }
            let max_c = r.max(g).max(b);
            let (final_r, final_g, final_b) = if max_c > 1.0 {
                let min_c = r.min(g).min(b);
                let compression_factor =
                    (1.0 - (max_c - 1.0) / (safe_highlight_compression - 1.0)).clamp(0.0, 1.0);
                let compressed_r = min_c + (r - min_c) * compression_factor;
                let compressed_g = min_c + (g - min_c) * compression_factor;
                let compressed_b = min_c + (b - min_c) * compression_factor;
                let compressed_max = compressed_r.max(compressed_g).max(compressed_b);
                if compressed_max > 1e-6 {
                    let rescale = max_c / compressed_max;
                    (compressed_r * rescale, compressed_g * rescale, compressed_b * rescale)
                } else {
                    (max_c, max_c, max_c)
                }
            } else {
                (r, g, b)
            };
            p[0] = final_r.clamp(0.0, clamp_limit);
            p[1] = final_g.clamp(0.0, clamp_limit);
            p[2] = final_b.clamp(0.0, clamp_limit);
        });
    }
}

/// Same math with the (never-taken for Bayer) linear/ungamma branch removed from the
/// per-pixel loop. Measurement-only reference for what hoisting that branch would give.
fn post_rescale_highlight_no_linear_branch(
    inter: &mut Intermediate,
    rescale_factor: f32,
    hc: f32,
    fast: bool,
) {
    let safe_hc = hc.max(1.01);
    let clamp_limit = if fast { 1.0 } else { safe_hc };
    if let Intermediate::ThreeColor(pixels) = inter {
        pixels.data.iter_mut().for_each(|p| {
            let r = (p[0] * rescale_factor).max(0.0);
            let g = (p[1] * rescale_factor).max(0.0);
            let b = (p[2] * rescale_factor).max(0.0);
            let max_c = r.max(g).max(b);
            let (fr, fg, fb) = if max_c > 1.0 {
                let min_c = r.min(g).min(b);
                let cf = (1.0 - (max_c - 1.0) / (safe_hc - 1.0)).clamp(0.0, 1.0);
                let cr = min_c + (r - min_c) * cf;
                let cg = min_c + (g - min_c) * cf;
                let cb = min_c + (b - min_c) * cf;
                let cm = cr.max(cg).max(cb);
                if cm > 1e-6 {
                    let s = max_c / cm;
                    (cr * s, cg * s, cb * s)
                } else {
                    (max_c, max_c, max_c)
                }
            } else {
                (r, g, b)
            };
            p[0] = fr.clamp(0.0, clamp_limit);
            p[1] = fg.clamp(0.0, clamp_limit);
            p[2] = fb.clamp(0.0, clamp_limit);
        });
    }
}

/// Step-by-step replica of raw_processing::develop_internal (quality mode, non-linear raw)
/// with timing between steps. Same calls, same order, same allocations.
fn develop_internal_timed(bytes: &[u8], hc: f32) -> Vec<(String, f64)> {
    let mut out = Vec::new();
    let t_all = Instant::now();
    let mut t = Instant::now();
    let mut lap = |name: &str, out: &mut Vec<(String, f64)>| {
        out.push((name.to_string(), ms(t.elapsed())));
        t = Instant::now();
    };
    let source = RawSource::new_from_slice(bytes);
    let decoder = rawler::get_decoder(&source).unwrap();
    let mut raw_image: RawImage = decoder
        .raw_image(&source, &RawDecodeParams::default(), false)
        .unwrap();
    lap("1 decode (get_decoder+raw_image)", &mut out);
    let metadata = decoder
        .raw_metadata(&source, &RawDecodeParams::default())
        .unwrap();
    let orientation = metadata
        .exif
        .orientation
        .map(rawler::decoders::Orientation::from_u16)
        .unwrap_or(rawler::decoders::Orientation::Normal);
    lap("2 raw_metadata", &mut out);
    let white = raw_image.whitelevel.0.first().cloned().unwrap_or(u16::MAX as u32) as f32;
    let black = raw_image.blacklevel.levels.first().map(|r| r.as_f32()).unwrap_or(0.0);
    for level in raw_image.whitelevel.0.iter_mut() {
        *level = u32::MAX;
    }
    let developer = production_developer(false);
    raw_image.wb_coeffs =
        crate::multi_exposure::neutralize_wb_if_multiexposure(raw_image.wb_coeffs, bytes);
    lap("3 setup", &mut out);
    let mut inter = developer.develop_intermediate(&raw_image).unwrap();
    lap("4 develop_intermediate (scale+PPG+WB/matrix+crop)", &mut out);
    drop(raw_image);
    lap("5 drop(raw_image)", &mut out);
    let rescale_factor = (u32::MAX as f32 - black) / (white - black).max(1.0);
    post_rescale_highlight(&mut inter, rescale_factor, hc, false);
    lap("6 rescale+highlight loop (serial)", &mut out);
    let img = intermediate_to_rgba32f(&inter);
    lap("7 to Rgba32F from_fn (serial)", &mut out);
    drop(inter);
    lap("8 drop(intermediate)", &mut out);
    let img = img.map(|i| crate::image_processing::apply_orientation(i, orientation));
    lap(&format!("8b apply_orientation ({:?})", orientation), &mut out);
    drop(img);
    lap("9 drop(output image)", &mut out);
    out.push(("TOTAL (excl. output drop)".to_string(), ms(t_all.elapsed()) - out.last().map(|x| x.1).unwrap_or(0.0)));
    out
}

/// Copy of develop_internal's ImageBuffer::from_fn conversion to Rgba32F (serial).
fn intermediate_to_rgba32f(inter: &Intermediate) -> Option<DynamicImage> {
    if let Intermediate::ThreeColor(pixels) = inter {
        let dim = inter.dim();
        let (width, height) = (dim.w as u32, dim.h as u32);
        let buffer = ImageBuffer::<Rgba<f32>, _>::from_fn(width, height, |x, y| {
            let p = pixels.data[(y * width + x) as usize];
            Rgba([p[0], p[1], p[2], 1.0])
        });
        Some(DynamicImage::ImageRgba32F(buffer))
    } else {
        None
    }
}

/// Uncached read (F_NOCACHE) to estimate cold external-SSD throughput.
fn read_nocache(path: &Path) -> std::io::Result<Vec<u8>> {
    use std::os::fd::AsRawFd;
    let mut f = fs::File::open(path)?;
    unsafe {
        libc::fcntl(f.as_raw_fd(), libc::F_NOCACHE, 1);
    }
    let mut buf = Vec::with_capacity(f.metadata()?.len() as usize);
    f.read_to_end(&mut buf)?;
    Ok(buf)
}

/// Replica of the read_exif_for_paths command body (minus tauri spawn_blocking).
fn read_exif_for_paths_core(paths: &[String]) -> HashMap<String, HashMap<String, String>> {
    paths
        .par_iter()
        .filter_map(|virtual_path| {
            let (source_path, _) = parse_virtual_path(virtual_path);
            let source_path_str = source_path.to_string_lossy().to_string();
            let map = if let Some(sidecar_exif) =
                crate::exif_processing::read_rrexif_sidecar(&source_path)
            {
                sidecar_exif
            } else if crate::file_management::is_cloud_placeholder(&source_path) {
                HashMap::new()
            } else if let Ok(mmap) = read_file_mapped(&source_path) {
                crate::exif_processing::read_exif_data(&source_path_str, &mmap)
            } else if let Ok(bytes) = fs::read(&source_path) {
                crate::exif_processing::read_exif_data(&source_path_str, &bytes)
            } else {
                HashMap::new()
            };
            if map.is_empty() {
                None
            } else {
                Some((virtual_path.clone(), map))
            }
        })
        .collect()
}

/// Replica of generate_single_thumbnail_and_cache for an *unedited* RAW
/// (sidecar parse -> cache hash -> embedded preview -> encode -> write).
fn thumbnail_unedited_raw(
    path: &Path,
    settings: &AppSettings,
    cache_dir: &Path,
) -> Option<(u32, u32, usize)> {
    let path_str = path.to_string_lossy().to_string();
    let (source_path, sidecar_path) = parse_virtual_path(&path_str);
    let adjustments_bytes = if let Ok(content) = fs::read_to_string(&sidecar_path)
        && let Ok(meta) = serde_json::from_str::<ImageMetadata>(&content)
    {
        let is_raw = crate::formats::is_raw_file(&path_str);
        let tm = resolve_tonemapper_override(settings, is_raw);
        let _ = is_image_edited(&meta.adjustments, is_raw, tm);
        serde_json::to_vec(&meta.adjustments).unwrap_or_default()
    } else {
        Vec::new()
    };
    let hash = bench_hooks::compute_thumbnail_cache_hash(&path_str, &adjustments_bytes)?;
    let target = settings.thumbnail_resolution.unwrap_or(720);
    // generate_thumbnail_data re-reads the sidecar; unedited RAW -> embedded preview.
    let _ = fs::read_to_string(&sidecar_path);
    let preview = bench_hooks::try_load_embedded_raw_preview(&source_path, target)?;
    let (w, h) = preview.dimensions();
    let data = bench_hooks::encode_thumbnail(&preview, target).ok()?;
    let _ = fs::write(cache_dir.join(format!("{}.jpg", hash)), &data);
    Some((w, h, data.len()))
}

// ---------------------------------------------------------------------------
// The benchmark
// ---------------------------------------------------------------------------

#[test]
#[ignore]
fn perf_bench() {
    let dir = std::env::var("RUSTROOM_BENCH_DIR").unwrap_or_else(|_| DEFAULT_DIR.to_string());
    let dir_path = PathBuf::from(&dir);
    if !dir_path.is_dir() {
        println!("perf_bench: input folder '{}' not found, skipping.", dir);
        return;
    }
    let reps = env_usize("RUSTROOM_BENCH_REPS", 3).max(1);
    let n_arw = env_usize("RUSTROOM_BENCH_ARWS", 5).max(1);
    let repo_root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .to_path_buf();
    let out_dir = repo_root.join("bench/out");
    let _ = fs::create_dir_all(&out_dir);
    let scratch = std::env::temp_dir().join("rustroom_perf_bench");
    let _ = fs::remove_dir_all(&scratch);
    fs::create_dir_all(scratch.join("thumbs")).unwrap();

    let mut rep = Report::default();
    let (settings, settings_src) = load_user_settings();
    let hc = settings.raw_highlight_compression.unwrap_or(2.5);
    let linear_mode = settings.linear_raw_mode.clone();
    let preview_dim = settings.editor_preview_resolution.unwrap_or(1920);
    let thumb_res = settings.thumbnail_resolution.unwrap_or(720);

    rep.section("Setup");
    rep.info(format!("input folder: {}", dir));
    rep.info(format!(
        "rayon global pool threads: {} (available_parallelism {:?})",
        rayon::current_num_threads(),
        std::thread::available_parallelism().map(|n| n.get()).ok()
    ));
    rep.info(format!(
        "settings: {} | editorPreviewResolution={} thumbnailResolution={} rawHighlightCompression={} linearRawMode={} rawPreprocessingColorNr={:?} rawPreprocessingSharpening={:?} livePreviewQuality={:?} useWgpuRenderer={:?}",
        settings_src,
        preview_dim,
        thumb_res,
        hc,
        linear_mode,
        settings.raw_preprocessing_color_nr,
        settings.raw_preprocessing_sharpening,
        settings.live_preview_quality,
        settings.use_wgpu_renderer
    ));
    rep.info(format!("reps per measurement: {} (+1 warmup)", reps));

    let mut all: Vec<PathBuf> = fs::read_dir(&dir_path)
        .unwrap()
        .filter_map(|e| e.ok().map(|e| e.path()))
        .collect();
    all.sort();
    let ext_is = |p: &Path, e: &str| {
        p.extension()
            .and_then(|x| x.to_str())
            .is_some_and(|x| x.eq_ignore_ascii_case(e))
    };
    let arws_all: Vec<PathBuf> = all.iter().filter(|p| ext_is(p, "arw")).cloned().collect();
    let jpgs_all: Vec<PathBuf> = all
        .iter()
        .filter(|p| ext_is(p, "jpg") || ext_is(p, "jpeg"))
        .cloned()
        .collect();
    let arws = pick_spread(&arws_all, n_arw);
    let jpgs = pick_spread(&jpgs_all, 2);
    // Untouched ARWs for the cold-read measurement (offset from the sampled ones).
    let cold_arws: Vec<PathBuf> = pick_spread(&arws_all, n_arw * 2 + 1)
        .into_iter()
        .filter(|p| !arws.contains(p))
        .take(n_arw)
        .collect();
    rep.info(format!(
        "folder contents: {} ARW, {} JPG, {} entries total",
        arws_all.len(),
        jpgs_all.len(),
        all.len()
    ));
    rep.info(format!(
        "sampled ARW: {}",
        arws.iter()
            .map(|p| format!(
                "{} ({:.1} MB)",
                p.file_name().unwrap().to_string_lossy(),
                fs::metadata(p).map(|m| m.len()).unwrap_or(0) as f64 / 1e6
            ))
            .collect::<Vec<_>>()
            .join(", ")
    ));
    rep.info(format!(
        "sampled JPG: {}",
        jpgs.iter()
            .map(|p| format!(
                "{} ({:.1} MB)",
                p.file_name().unwrap().to_string_lossy(),
                fs::metadata(p).map(|m| m.len()).unwrap_or(0) as f64 / 1e6
            ))
            .collect::<Vec<_>>()
            .join(", ")
    ));

    // Sidecar-safe paths: load_base_image_from_bytes calls persist_exif_if_missing(path),
    // which may write a sidecar next to `path`. Point it at a scratch copy of the real sidecar
    // so the user's folder is never written by the decode benchmarks.
    let scratch_path_for = |p: &Path| -> String {
        let name = p.file_name().unwrap();
        let sc = p.with_file_name(format!("{}.rrdata", name.to_string_lossy()));
        let dst = scratch.join(format!("{}.rrdata", name.to_string_lossy()));
        if sc.exists() && !dst.exists() {
            let _ = fs::copy(&sc, &dst);
        }
        scratch.join(name).to_string_lossy().to_string()
    };

    // -----------------------------------------------------------------------
    // 1. Folder listing + EXIF
    // -----------------------------------------------------------------------
    rep.section("1. Folder listing + EXIF (warm OS file cache)");
    let (s, listed) = bench(reps, || {
        bench_hooks::list_images_in_dir_no_handle(&dir, &settings).unwrap()
    });
    rep.add(
        &format!("list_images_in_dir core ({} images)", listed.len()),
        s,
        "read_dir + ext filter + per-file stat + sidecar JSON parse + is_edited + grouping (rayon)",
    );
    let paths: Vec<String> = listed.iter().map(|f| f.path.clone()).collect();
    let (s, exif) = bench(reps, || read_exif_for_paths_core(&paths));
    rep.add(
        &format!("read_exif_for_paths ({} paths -> {} maps)", paths.len(), exif.len()),
        s,
        "served from .rrdata sidecar exif (sidecars already populated)",
    );
    // Per-file sidecar parse cost (the dominant listing cost)
    let (s, _) = bench(reps, || {
        paths
            .iter()
            .take(200)
            .map(|p| {
                let (_, sc) = parse_virtual_path(p);
                crate::exif_processing::load_sidecar(&sc).rating as usize
            })
            .sum::<usize>()
    });
    rep.add(
        "load_sidecar x200 serial (per-file JSON parse)",
        s.iter().map(|v| v / 200.0).collect(),
        "per file; sidecars embed full EXIF map (~10 KB JSON each)",
    );
    // EXIF from file bytes (first visit, no sidecar yet)
    let mut exif_raw_samples = Vec::new();
    let mut exif_jpg_samples = Vec::new();
    for p in arws.iter().chain(jpgs.iter()) {
        let ps = p.to_string_lossy().to_string();
        let (s, _) = bench(reps, || {
            let mmap = read_file_mapped(p).unwrap();
            crate::exif_processing::read_exif_data_from_bytes(&ps, &mmap).len()
        });
        if ext_is(p, "arw") {
            exif_raw_samples.extend(s);
        } else {
            exif_jpg_samples.extend(s);
        }
    }
    rep.add(
        "read_exif_data_from_bytes, ARW (no-sidecar path)",
        exif_raw_samples,
        "mmap + EXIF parse per file",
    );
    rep.add(
        "read_exif_data_from_bytes, JPG (no-sidecar path)",
        exif_jpg_samples,
        "mmap + EXIF parse per file",
    );

    // -----------------------------------------------------------------------
    // 2. Thumbnails
    // -----------------------------------------------------------------------
    rep.section("2. Thumbnails (per image)");
    let thumb_dir = scratch.join("thumbs");
    for p in &arws {
        let (s, r) = bench(reps, || thumbnail_unedited_raw(p, &settings, &thumb_dir));
        rep.acc(
            "unedited ARW thumbnail total (generate_single_thumbnail_and_cache)",
            s,
            "sidecar + hash + embedded JPEG preview decode + downscale + JPEG q75 encode + write",
        );
        if let Some((w, h, sz)) = r {
            rep.acc_info_once(&format!(
                "embedded ARW preview size: {}x{}, thumbnail jpeg ~{} KB",
                w,
                h,
                sz / 1024
            ));
        }
        let (s, prev) = bench(reps, || {
            bench_hooks::try_load_embedded_raw_preview(p, thumb_res).unwrap()
        });
        rep.acc(
            "  - try_load_embedded_raw_preview",
            s,
            "mmap + EXIF parse + JPEG decode of embedded preview",
        );
        let (s, _) = bench(reps, || downscale_f32_image(&prev, thumb_res, thumb_res));
        rep.acc(
            "  - downscale_f32_image to thumb (inside encode)",
            s,
            "converts u8 preview to Rgb32F first",
        );
        let (s, _) = bench(reps, || bench_hooks::encode_thumbnail(&prev, thumb_res).unwrap());
        rep.acc("  - encode_thumbnail (downscale + JPEG encode)", s, "");
    }
    for p in &jpgs {
        let ps = p.to_string_lossy().to_string();
        let (s, _) = bench(reps, || {
            let mmap = read_file_mapped(p).unwrap();
            let img = crate::image_loader::load_and_composite(
                &mmap,
                &ps,
                &serde_json::Value::Null,
                true,
                &settings,
                None,
            )
            .unwrap();
            bench_hooks::encode_thumbnail(&img, thumb_res).unwrap().len()
        });
        rep.acc(
            "unedited JPG thumbnail total",
            s,
            "full JPEG decode -> Rgb32F + orientation + downscale + encode (no AgX: default non-raw tonemapper=basic)",
        );
    }

    // -----------------------------------------------------------------------
    // 3. RAW decode + demosaic
    // -----------------------------------------------------------------------
    rep.section("3. RAW decode + demosaic (per ARW)");
    let mut cold = Vec::new();
    let mut cold_mbps = Vec::new();
    for p in &cold_arws {
        let t = Instant::now();
        if let Ok(b) = read_nocache(p) {
            let e = t.elapsed();
            cold.push(ms(e));
            cold_mbps.push(b.len() as f64 / 1e6 / e.as_secs_f64());
        }
    }
    if !cold_mbps.is_empty() {
        let (m, _, _) = stats(&cold_mbps);
        rep.add(
            "file read, cold (F_NOCACHE, untouched ARWs)",
            cold,
            &format!("external SSD, median {:.0} MB/s", m),
        );
    }

    let mut single_thread_done = false;
    for (idx, p) in arws.iter().enumerate() {
        let spath = scratch_path_for(p);
        let (s, bytes) = bench(reps, || fs::read(p).unwrap());
        rep.acc("file read, warm (fs::read)", s, "page-cache hit");
        let (s, _) = bench(reps, || read_file_mapped(p).unwrap().len());
        rep.acc(
            "read_file_mapped (mmap open only)",
            s,
            "pages fault in lazily during decode",
        );

        let (s, _) = bench(reps, || {
            let source = RawSource::new_from_slice(&bytes);
            rawler::get_decoder(&source).is_ok()
        });
        rep.acc("rawler::get_decoder", s, "TIFF/IFD parse");
        let (s, (raw, rescale_factor)) = bench(reps, || decode_like_production(&bytes));
        rep.acc(
            "rawler decode (get_decoder + raw_image)",
            s,
            "Sony LJPEG/ARW decompression -> u16 CFA",
        );
        let (s, _) = bench(reps, || {
            let source = RawSource::new_from_slice(&bytes);
            let d = rawler::get_decoder(&source).unwrap();
            d.raw_metadata(&source, &RawDecodeParams::default()).is_ok()
        });
        rep.acc(
            "rawler get_decoder + raw_metadata",
            s,
            "called separately in develop_internal (re-parses)",
        );
        if idx == 0 {
            let cfa = match &raw.photometric {
                RawPhotometricInterpretation::Cfa(c) => format!("CFA {}", c.cfa.name),
                other => format!("{:?}", other),
            };
            rep.info(format!(
                "RAW sensor: {}x{} cpp={} bps={} {} active_area={:?} crop_area={:?} make/model={} {}",
                raw.width,
                raw.height,
                raw.cpp,
                raw.bps,
                cfa,
                raw.active_area,
                raw.crop_area,
                raw.clean_make,
                raw.clean_model
            ));
        }

        // Step-subset breakdown of RawDevelop::develop_intermediate
        let mut dev_rescale = RawDevelop::default();
        dev_rescale.steps = vec![ProcessingStep::Rescale];
        let (s, _) = bench(reps, || dev_rescale.develop_intermediate(&raw).unwrap().dim());
        rep.acc(
            "develop_intermediate [Rescale] only",
            s,
            "rawimage.clone() + u16->f32 (serial) + blacklevel scaling + f32 copy into PixF32",
        );
        let mut dev_demosaic = RawDevelop::default();
        dev_demosaic.steps = vec![
            ProcessingStep::Rescale,
            ProcessingStep::Demosaic,
            ProcessingStep::CropActiveArea,
        ];
        let (s, _) = bench(reps, || dev_demosaic.develop_intermediate(&raw).unwrap().dim());
        rep.acc(
            "develop_intermediate [Rescale,Demosaic(PPG),CropActive]",
            s,
            "",
        );
        let mut dev_calib = RawDevelop::default();
        dev_calib.steps = vec![
            ProcessingStep::Rescale,
            ProcessingStep::Demosaic,
            ProcessingStep::CropActiveArea,
            ProcessingStep::WhiteBalance,
            ProcessingStep::Calibrate,
        ];
        let (s, _) = bench(reps, || dev_calib.develop_intermediate(&raw).unwrap().dim());
        rep.acc(
            "develop_intermediate [.. + WhiteBalance, Calibrate]",
            s,
            "adds map_3ch_to_rgb (rayon par_iter + collect_into_vec)",
        );
        let dev_prod = production_developer(false);
        let (s, inter) = bench(reps, || dev_prod.develop_intermediate(&raw).unwrap());
        rep.acc(
            "develop_intermediate production steps (quality)",
            s,
            "+ WB + camera->sRGB matrix (map_3ch_to_rgb, rayon) + CropDefault (serial copy)",
        );
        let dev_fast = production_developer(true);
        let (s, _) = bench(reps, || dev_fast.develop_intermediate(&raw).unwrap().dim());
        rep.acc(
            "develop_intermediate production steps (fast/superpixel)",
            s,
            "quarter-res superpixel",
        );

        // Direct PPG timing on pre-scaled data
        let mut scaled = raw.clone();
        let (s, _) = bench(reps, || {
            let mut r = raw.clone();
            r.apply_scaling().unwrap();
            r.width
        });
        rep.acc(
            "  - raw.clone() + apply_scaling",
            s,
            "u16->f32 convert is serial (convert_to_f32_unscaled)",
        );
        scaled.apply_scaling().unwrap();
        let (s, pixels) = bench(reps, || {
            PixF32::new_with(scaled.data.as_f32().into_owned(), scaled.width, scaled.height)
        });
        rep.acc("  - f32 Vec copy into PixF32", s, "serial memcpy of ~130 MB");
        if let RawPhotometricInterpretation::Cfa(config) = &scaled.photometric {
            let roi = scaled.active_area.unwrap_or(pixels.rect());
            let ppg = PPGDemosaic::new();
            let (s, out) = bench(reps, || ppg.demosaic(&pixels, &config.cfa, &config.colors, roi));
            rep.acc(
                "  - PPG demosaic (multi-threaded, global rayon pool)",
                s,
                "expand_bayer + borders(serial) + green + rb@g + rb@non-g (rayon rows)",
            );
            if idx == 0 {
                rep.info(format!(
                    "PPG output: {}x{} RGB f32 ({:.0} MB)",
                    out.width,
                    out.height,
                    (out.width * out.height * 12) as f64 / 1e6
                ));
            }
            drop(out);
            if !single_thread_done {
                let pool = rayon::ThreadPoolBuilder::new()
                    .num_threads(1)
                    .build()
                    .unwrap();
                let (s, _) = pool.install(|| {
                    bench(1, || {
                        ppg.demosaic(&pixels, &config.cfa, &config.colors, roi).width
                    })
                });
                rep.acc(
                    "  - PPG demosaic (1 thread)",
                    s,
                    "same call inside a 1-thread rayon pool (file 1 only)",
                );
            }
        }
        drop(pixels);
        drop(scaled);

        // Post-develop passes in develop_internal (copied code)
        let mut post_samples = Vec::new();
        let mut post_nb_samples = Vec::new();
        let mut conv_samples = Vec::new();
        for _ in 0..=reps {
            let mut i = inter.clone();
            let t = Instant::now();
            post_rescale_highlight_no_linear_branch(&mut i, rescale_factor, hc, false);
            post_nb_samples.push(ms(t.elapsed()));
            let mut i = inter.clone();
            let t = Instant::now();
            post_rescale_highlight(&mut i, rescale_factor, hc, false);
            post_samples.push(ms(t.elapsed()));
            let t = Instant::now();
            let img = intermediate_to_rgba32f(&i);
            conv_samples.push(ms(t.elapsed()));
            drop(img);
        }
        post_samples.remove(0);
        post_nb_samples.remove(0);
        conv_samples.remove(0);
        rep.acc(
            "  - post: rescale + highlight compression loop",
            post_samples,
            "serial iter_mut in raw_processing.rs develop_internal",
        );
        rep.acc(
            "  - post loop, same math w/o per-pixel linear branch (reference)",
            post_nb_samples,
            "measurement-only variant: shows cost of the untaken powf branch inside the loop",
        );
        rep.acc(
            "  - post: Intermediate -> Rgba32F (ImageBuffer::from_fn)",
            conv_samples,
            "serial per-pixel closure, 16 B/px output",
        );
        drop(inter);
        drop(raw);

        // In-situ breakdown: develop_internal's steps copied with Instants between them.
        let mut steps_acc: Vec<(String, Vec<f64>)> = Vec::new();
        for it in 0..=reps {
            let steps = develop_internal_timed(&bytes, hc);
            if it == 0 {
                continue;
            }
            for (k, v) in steps {
                if let Some(e) = steps_acc.iter_mut().find(|(n, _)| *n == k) {
                    e.1.push(v);
                } else {
                    steps_acc.push((k, vec![v]));
                }
            }
        }
        for (k, v) in steps_acc {
            rep.acc(&format!("  in-situ develop_internal: {}", k), v, "");
        }

        // End-to-end production calls
        let (s, dev) = bench(reps, || {
            crate::raw_processing::develop_raw_image(&bytes, false, hc, linear_mode.clone(), None)
                .unwrap()
        });
        rep.acc(
            "develop_raw_image(fast_demosaic=false)",
            s,
            "decode+metadata+develop+post+orientation",
        );
        if idx == 0 {
            rep.info(format!(
                "developed image: {}x{} {:?}",
                dev.width(),
                dev.height(),
                dev.color()
            ));
        }
        if !single_thread_done {
            let pool = rayon::ThreadPoolBuilder::new()
                .num_threads(1)
                .build()
                .unwrap();
            let (s, _) = pool.install(|| {
                bench(1, || {
                    crate::raw_processing::develop_raw_image(
                        &bytes,
                        false,
                        hc,
                        linear_mode.clone(),
                        None,
                    )
                    .unwrap()
                    .width()
                })
            });
            rep.acc(
                "develop_raw_image(false) (1 thread)",
                s,
                "1-thread rayon pool (file 1 only) -> parallel speedup reference",
            );
        }
        let (s, fastimg) = bench(reps, || {
            crate::raw_processing::develop_raw_image(&bytes, true, hc, linear_mode.clone(), None)
                .unwrap()
        });
        rep.acc("develop_raw_image(fast_demosaic=true)", s, "");
        if idx == 0 {
            rep.info(format!(
                "fast-demosaic image: {}x{}",
                fastimg.width(),
                fastimg.height()
            ));
        }
        drop(fastimg);

        let color_nr_setting = settings.raw_preprocessing_color_nr.unwrap_or(0.5);
        let color_nr_amount = if color_nr_setting <= 0.0 {
            0.0
        } else {
            (12.0 / color_nr_setting.clamp(0.01, 1.0) - 10.0).max(0.1)
        };
        let sharp = settings.raw_preprocessing_sharpening.unwrap_or(0.35);
        let mut enh = Vec::new();
        for _ in 0..=reps {
            let mut i = dev.clone();
            let t = Instant::now();
            remove_raw_artifacts_and_enhance(&mut i, color_nr_amount, sharp);
            enh.push(ms(t.elapsed()));
        }
        enh.remove(0);
        rep.acc(
            "remove_raw_artifacts_and_enhance (color NR + sharpen)",
            enh,
            "rayon; runs on every quality load (load_image)",
        );
        drop(dev);

        let (s, base) = bench(reps, || {
            crate::image_loader::load_base_image_from_bytes(&bytes, &spath, false, &settings, None)
                .unwrap()
        });
        rep.acc(
            "load_base_image_from_bytes(fast=false) TOTAL",
            s,
            "= load_image decode path (develop + enhance)",
        );
        if idx == 0 {
            rep.info(format!(
                "load_image output: {}x{} {:?} ({:.0} MB in RAM)",
                base.width(),
                base.height(),
                base.color(),
                (base.width() as f64 * base.height() as f64 * 12.0) / 1e6
            ));
        }
        drop(base);
        single_thread_done = true;
    }

    // -----------------------------------------------------------------------
    // 4-6. GPU: image open, slider edit, analytics
    // -----------------------------------------------------------------------
    let Some((ctx, adapter_name)) = make_headless_gpu_context() else {
        rep.info("GPU: no adapter, skipping GPU stages".to_string());
        finish(&rep, &out_dir);
        return;
    };
    rep.section("4. Image open / switch (backend critical path, per ARW)");
    rep.info(format!(
        "GPU adapter: {} (headless, no surface; present() not measured)",
        adapter_name
    ));
    let tm = resolve_tonemapper_override(&settings, true);
    let open_adj = serde_json::json!({});

    // Pre-create a preview-sized display processor once (the app keeps one in AppState
    // and only recreates it when a bigger image comes in).
    let t = Instant::now();
    let mut preview_proc: Option<(GpuProcessor, u32, u32)> = None;
    let mut first_proc_ms = None;
    let mut last_preview: Option<(DynamicImage, wgpu::Texture, wgpu::TextureView)> = None;

    for (idx, p) in arws.iter().enumerate() {
        let spath = scratch_path_for(p);
        let mut s_read = Vec::new();
        let mut s_load = Vec::new();
        let mut s_exif = Vec::new();
        let mut s_transform = Vec::new();
        let mut s_down = Vec::new();
        let mut s_f16 = Vec::new();
        let mut s_tex = Vec::new();
        let mut s_render = Vec::new();
        let mut s_total = Vec::new();
        for it in 0..=reps {
            let t0 = Instant::now();
            // load_image: mmap + quality develop + enhance + exif
            let t = Instant::now();
            let mmap = read_file_mapped(p).unwrap();
            let d_read = ms(t.elapsed());
            let t = Instant::now();
            // Production load_image path: quality develop, NR + sharpening deferred to background.
            let (img, _needs_enhance) = crate::image_loader::load_base_image_inner(
                &mmap, &spath, false, &settings, None, true,
            )
            .unwrap();
            let d_load = ms(t.elapsed());
            let t = Instant::now();
            let _exif = crate::exif_processing::read_exif_data(&spath, &mmap);
            let d_exif = ms(t.elapsed());
            drop(mmap);
            // apply_adjustments (non-interactive, first render): compute_full_transformed_res
            let t = Instant::now();
            let (transformed, _off) =
                crate::adjustment_utils::apply_all_transformations(&img, &open_adj);
            let full = Arc::new(transformed.into_owned());
            let d_transform = ms(t.elapsed());
            drop(img);
            let t = Instant::now();
            let preview = downscale_f32_image(&full, preview_dim, preview_dim);
            let d_down = ms(t.elapsed());
            drop(full);
            let (pw, ph) = preview.dimensions();
            let t = Instant::now();
            let f16data = to_rgba_f16(&preview);
            let d_f16 = ms(t.elapsed());
            let t = Instant::now();
            let (tex, view) = create_input_texture(&ctx, &f16data, pw, ph);
            gpu_wait(&ctx);
            let d_tex = ms(t.elapsed());
            if preview_proc
                .as_ref()
                .is_none_or(|(_, w, h)| *w < pw || *h < ph)
            {
                let t = Instant::now();
                let proc_ = GpuProcessor::new(ctx.clone(), padded(pw), padded(ph), true).unwrap();
                gpu_wait(&ctx);
                if first_proc_ms.is_none() {
                    first_proc_ms = Some(ms(t.elapsed()));
                }
                preview_proc = Some((proc_, padded(pw), padded(ph)));
            }
            let (proc_, _, _) = preview_proc.as_ref().unwrap();
            let t = Instant::now();
            render_display(&ctx, proc_, &view, pw, ph, &open_adj, tm, None);
            let d_render = ms(t.elapsed());
            let d_total = ms(t0.elapsed());
            if it > 0 {
                s_read.push(d_read);
                s_load.push(d_load);
                s_exif.push(d_exif);
                s_transform.push(d_transform);
                s_down.push(d_down);
                s_f16.push(d_f16);
                s_tex.push(d_tex);
                s_render.push(d_render);
                s_total.push(d_total);
            }
            if idx == 0 && it == 0 {
                rep.info(format!(
                    "editor preview: {}x{} (editorPreviewResolution={}), GPU processor {}x{}",
                    pw,
                    ph,
                    preview_dim,
                    padded(pw),
                    padded(ph)
                ));
            }
            last_preview = Some((preview, tex, view));
        }
        rep.acc("open: read_file_mapped", s_read, "");
        rep.acc(
            "open: load_image develop (quality, enhance deferred)",
            s_load,
            "NR + sharpening now runs in the background after the photo is shown",
        );
        rep.acc("open: read_exif_data", s_exif, "sidecar hit");
        rep.acc(
            "open: apply_all_transformations + into_owned",
            s_transform,
            "compute_full_transformed_res clones full-res image even with no geometry edits",
        );
        rep.acc(
            &format!("open: downscale_f32_image -> {}", preview_dim),
            s_down,
            "",
        );
        rep.acc("open: to_rgba_f16 (preview)", s_f16, "CPU f32->f16 + RGBA expand");
        rep.acc(
            "open: create_texture_with_data + GPU wait (preview)",
            s_tex,
            "",
        );
        rep.acc(
            "open: first GPU render, display path (+wait)",
            s_render,
            "run(skip_readback) + copy to output tex",
        );
        rep.acc(
            "open: TOTAL backend critical path",
            s_total,
            "load_image + first apply_adjustments (excl. IPC, present, processor creation)",
        );
    }
    let _ = t;
    if let Some(v) = first_proc_ms {
        rep.add(
            "GpuProcessor::new (preview-size, with_display) first time",
            vec![v],
            "shader compile + pipelines + textures; once per session / size increase",
        );
    }

    // -----------------------------------------------------------------------
    // 5. Real-time slider edit
    // -----------------------------------------------------------------------
    rep.section("5. Slider edit: GPU re-render of uploaded image");
    let n_slider = 20usize;
    let mut readback_img: Option<DynamicImage> = None;
    if let (Some((proc_, _, _)), Some((preview, _tex, view))) = (&preview_proc, &last_preview) {
        let (pw, ph) = preview.dimensions();
        // (a) readback path
        let mut s = Vec::new();
        for i in 0..=n_slider {
            let adj = edit_adjustments(-1.0 + i as f64 * 0.1);
            let t = Instant::now();
            let out = render_readback(proc_, view, pw, ph, &adj, tm, None);
            if i > 0 {
                s.push(ms(t.elapsed()));
            }
            readback_img = Some(out);
        }
        rep.add(
            &format!("preview {}x{} render + CPU readback", pw, ph),
            s,
            "run(skip_readback=false): what non-wgpu path / analytics needs",
        );
        // (b) display path
        let mut s = Vec::new();
        for i in 0..=n_slider {
            let adj = edit_adjustments(-1.0 + i as f64 * 0.1);
            let t = Instant::now();
            render_display(&ctx, proc_, view, pw, ph, &adj, tm, None);
            if i > 0 {
                s.push(ms(t.elapsed()));
            }
        }
        rep.add(
            &format!("preview {}x{} render, display path (+GPU wait)", pw, ph),
            s,
            "use_wgpu_renderer=true path; surface present not included",
        );
        // (c) same with no edits at all (default adjustments) for reference
        let mut s = Vec::new();
        for i in 0..=n_slider {
            let t = Instant::now();
            render_display(&ctx, proc_, view, pw, ph, &open_adj, tm, None);
            if i > 0 {
                s.push(ms(t.elapsed()));
            }
        }
        rep.add(
            &format!("preview {}x{} render, display path, default adj", pw, ph),
            s,
            "4 blur passes run regardless of slider values",
        );
        let bb = BlurBench::new(&ctx, pw.min(2304), ph.min(2304));
        bench_blurs(&mut rep, &ctx, &bb, view, pw, ph, (0, 0, pw, ph), "preview", 10);
        drop(bb);
        // mask texture cost (zero-filled, 2 layers, re-created every run)
        let mut s = Vec::new();
        for i in 0..=n_slider {
            let t = Instant::now();
            let zeros = vec![0u8; (pw * ph * 2) as usize];
            let _m = ctx.device.create_texture_with_data(
                &ctx.queue,
                &wgpu::TextureDescriptor {
                    label: Some("bench mask"),
                    size: wgpu::Extent3d {
                        width: pw,
                        height: ph,
                        depth_or_array_layers: 2,
                    },
                    mip_level_count: 1,
                    sample_count: 1,
                    dimension: wgpu::TextureDimension::D2,
                    format: wgpu::TextureFormat::R8Unorm,
                    usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
                    view_formats: &[],
                },
                TextureDataOrder::MipMajor,
                &zeros,
            );
            gpu_wait(&ctx);
            if i > 0 {
                s.push(ms(t.elapsed()));
            }
        }
        rep.add(
            "  - per-run empty mask texture (preview, 2 layers)",
            s,
            "allocated+uploaded inside every GpuProcessor::run",
        );
    }

    // -----------------------------------------------------------------------
    // 6. Analytics
    // -----------------------------------------------------------------------
    rep.section("6. Analytics on preview output (after each render)");
    if let Some(img) = &readback_img {
        let (s, _) = bench(10, || calculate_histogram_from_image(img).is_ok());
        rep.add(
            &format!("calculate_histogram_from_image {}x{}", img.width(), img.height()),
            s,
            "",
        );
        let (s, _) = bench(10, || calculate_waveform_from_image(img, None).is_ok());
        rep.add(
            &format!("calculate_waveform_from_image {}x{} (all)", img.width(), img.height()),
            s,
            "",
        );
        let (s, _) = bench(10, || calculate_waveform_from_image(img, Some("luma")).is_ok());
        rep.add("calculate_waveform_from_image (luma only)", s, "");
    }
    drop(preview_proc);
    drop(last_preview);
    gpu_wait(&ctx);

    // -----------------------------------------------------------------------
    // 2b. Edited-thumbnail path (GPU)
    // -----------------------------------------------------------------------
    rep.section("2b. Edited ARW thumbnail (GPU path, per image)");
    {
        let mut thumb_proc: Option<(GpuProcessor, u32, u32)> = None;
        let adj = edit_adjustments(0.3);
        for p in arws.iter().take(3) {
            let spath = scratch_path_for(p);
            let mut s_total = Vec::new();
            let mut s_load = Vec::new();
            let mut s_scale = Vec::new();
            let mut s_gpu = Vec::new();
            for it in 0..=reps {
                let t0 = Instant::now();
                let mmap = read_file_mapped(p).unwrap();
                let t = Instant::now();
                let img = crate::image_loader::load_and_composite(
                    &mmap, &spath, &adj, true, &settings, None,
                )
                .unwrap();
                let d_load = ms(t.elapsed());
                let t = Instant::now();
                let _sf = crate::raw_processing::get_fast_demosaic_scale_factor(
                    &mmap,
                    img.width(),
                    img.height(),
                );
                let d_scale = ms(t.elapsed());
                let warped = apply_geometry_warp(Cow::Borrowed(&img), &adj);
                let blurred = crate::lens_blur::apply_lens_blur(warped, &adj);
                let rotated = apply_coarse_rotation(blurred, 0);
                let base = downscale_f32_image(&rotated, thumb_res, thumb_res);
                drop(rotated);
                let (bw, bh) = base.dimensions();
                let t = Instant::now();
                let f16data = to_rgba_f16(&base);
                let (_tex, view) = create_input_texture(&ctx, &f16data, bw, bh);
                if thumb_proc
                    .as_ref()
                    .is_none_or(|(_, w, h)| *w < bw || *h < bh)
                {
                    thumb_proc = Some((
                        GpuProcessor::new(ctx.clone(), padded(bw), padded(bh), false).unwrap(),
                        padded(bw),
                        padded(bh),
                    ));
                }
                let out =
                    render_readback(&thumb_proc.as_ref().unwrap().0, &view, bw, bh, &adj, tm, None);
                let d_gpu = ms(t.elapsed());
                let _jpg = bench_hooks::encode_thumbnail(&out, thumb_res).unwrap();
                let d_total = ms(t0.elapsed());
                if it > 0 {
                    s_total.push(d_total);
                    s_load.push(d_load);
                    s_scale.push(d_scale);
                    s_gpu.push(d_gpu);
                }
            }
            rep.acc(
                "edited ARW thumbnail total",
                s_total,
                "fast demosaic + scale-factor probe + warp + downscale + GPU + encode",
            );
            rep.acc("  - load_and_composite(fast=true)", s_load, "superpixel develop, no enhance");
            rep.acc(
                "  - get_fast_demosaic_scale_factor",
                s_scale,
                "re-parses RAW (dummy decode) just to get dims",
            );
            rep.acc(
                "  - GPU upload + render + readback (720px)",
                s_gpu,
                "processor created once (excluded after warmup)",
            );
        }
    }

    // -----------------------------------------------------------------------
    // 5b. Full-resolution renders (export / 1:1 zoom reference) + ROI
    // -----------------------------------------------------------------------
    rep.section("5b. Full-resolution GPU renders (reference for export / zoom 1:1)");
    for (idx, p) in arws.iter().take(2).enumerate() {
        let spath = scratch_path_for(p);
        let mmap = read_file_mapped(p).unwrap();
        let img =
            crate::image_loader::load_base_image_from_bytes(&mmap, &spath, false, &settings, None)
                .unwrap();
        drop(mmap);
        let (fw, fh) = img.dimensions();
        let t = Instant::now();
        let f16data = to_rgba_f16(&img);
        let d_f16 = ms(t.elapsed());
        drop(img);
        let t = Instant::now();
        let (_tex, view) = create_input_texture(&ctx, &f16data, fw, fh);
        gpu_wait(&ctx);
        let d_tex = ms(t.elapsed());
        drop(f16data);
        rep.acc(
            "full-res to_rgba_f16",
            vec![d_f16],
            "to_rgba32f (528 MB temp) + f16 convert, serial",
        );
        rep.acc("full-res create_texture_with_data + wait", vec![d_tex], "");
        let t = Instant::now();
        let proc_ = GpuProcessor::new(ctx.clone(), padded(fw), padded(fh), true).unwrap();
        gpu_wait(&ctx);
        rep.acc(
            "GpuProcessor::new full-res with_display",
            vec![ms(t.elapsed())],
            "",
        );
        if idx == 0 {
            rep.info(format!(
                "full-res render size: {}x{} -> {} tiles of {}px",
                fw,
                fh,
                fw.div_ceil(2048) * fh.div_ceil(2048),
                2048
            ));
        }
        let adj = edit_adjustments(0.2);
        let fr_reps = reps.min(3);
        let (s, out) = bench(fr_reps, || render_readback(&proc_, &view, fw, fh, &adj, tm, None));
        rep.acc(
            "full-res render + CPU readback (tiled)",
            s,
            "export/zoom path; per-tile blocking map_async",
        );
        drop(out);
        let (s, _) = bench(fr_reps, || render_display(&ctx, &proc_, &view, fw, fh, &adj, tm, None));
        rep.acc("full-res render, display path (+GPU wait)", s, "no readback");
        let roi = Roi {
            x: (fw / 2).saturating_sub(800),
            y: (fh / 2).saturating_sub(500),
            width: 1600.min(fw),
            height: 1000.min(fh),
        };
        let (s, _) = bench(reps, || {
            render_readback(&proc_, &view, fw, fh, &adj, tm, Some(roi))
        });
        rep.acc(
            "full-res ROI 1600x1000 (center) + readback",
            s,
            "RenderRequest.roi; touches 4 tiles when centered",
        );
        let (s, _) = bench(reps, || {
            render_display(&ctx, &proc_, &view, fw, fh, &adj, tm, Some(roi))
        });
        rep.acc(
            "full-res ROI 1600x1000 (center), display path",
            s,
            "incl. full-size zero mask upload (w*h*2 B) per run",
        );
        let roi_aligned = Roi {
            x: 0,
            y: 0,
            width: 1600.min(fw),
            height: 1000.min(fh),
        };
        let (s, _) = bench(reps, || {
            render_display(&ctx, &proc_, &view, fw, fh, &adj, tm, Some(roi_aligned))
        });
        rep.acc(
            "full-res ROI 1600x1000 (tile-aligned, 1 tile), display",
            s,
            "",
        );
        if idx == 0 {
            // one interior full-res tile: 2048 + 2*128 overlap
            let bb = BlurBench::new(&ctx, 2304, 2304);
            bench_blurs(
                &mut rep,
                &ctx,
                &bb,
                &view,
                fw,
                fh,
                (2048 - 128, 2048 - 128, 2304.min(fw - 1920), 2304.min(fh - 1920)),
                "full-res tile",
                reps,
            );
            drop(bb);
        }
        // full-res zero mask upload alone
        let (s, _) = bench(reps, || {
            let zeros = vec![0u8; (fw as usize) * (fh as usize) * 2];
            let _m = ctx.device.create_texture_with_data(
                &ctx.queue,
                &wgpu::TextureDescriptor {
                    label: Some("bench mask"),
                    size: wgpu::Extent3d {
                        width: fw,
                        height: fh,
                        depth_or_array_layers: 2,
                    },
                    mip_level_count: 1,
                    sample_count: 1,
                    dimension: wgpu::TextureDimension::D2,
                    format: wgpu::TextureFormat::R8Unorm,
                    usage: wgpu::TextureUsages::TEXTURE_BINDING | wgpu::TextureUsages::COPY_DST,
                    view_formats: &[],
                },
                TextureDataOrder::MipMajor,
                &zeros,
            );
            gpu_wait(&ctx);
        });
        rep.acc(
            "  - per-run empty mask texture (full-res, 2 layers)",
            s,
            "part of every full-res/ROI run",
        );
        drop(proc_);
        gpu_wait(&ctx);
    }

    finish(&rep, &out_dir);
    let _ = fs::remove_dir_all(&scratch);
}

impl Report {
    fn acc_info_once(&mut self, s: &str) {
        if !self.info.iter().any(|i| i == s) {
            self.info(s.to_string());
        }
    }
}

fn finish(rep: &Report, out_dir: &Path) {
    // Print per-row summary for accumulated rows too.
    rep.print_final_table();
    let md = rep.to_markdown();
    let path = out_dir.join("backend_bench.md");
    match fs::write(&path, md) {
        Ok(_) => println!("\nWrote {}", path.display()),
        Err(e) => println!("\nFailed to write {}: {}", path.display(), e),
    }
}


// ---------------------------------------------------------------------------
// Main-shader profiling by ablation: compile variants of shader.wgsl with one section
// removed and measure the display-path render at editor preview size (1920x1280).
// Run: cargo test --lib perf_shader_profile -- --ignored --nocapture --test-threads=1
// ---------------------------------------------------------------------------

#[test]
#[ignore]
fn perf_shader_profile() {
    let Some((ctx, gpu_name)) = make_headless_gpu_context() else {
        eprintln!("no GPU adapter; skipping");
        return;
    };
    let (w, h) = (1920u32, 1280u32);
    // Deterministic synthetic image (smooth gradients + noise) — shader cost doesn't depend on content much.
    let img = DynamicImage::ImageRgba32F(ImageBuffer::from_fn(w, h, |x, y| {
        let n = ((x.wrapping_mul(73856093) ^ y.wrapping_mul(19349663)) % 1000) as f32 / 1000.0;
        Rgba([x as f32 / w as f32 * 0.8 + n * 0.1, y as f32 / h as f32 * 0.7 + n * 0.1, 0.4 + n * 0.2, 1.0])
    }));
    let data = to_rgba_f16(&img);
    let (_tex, view) = create_input_texture(&ctx, &data, w, h);
    let base_src = include_str!("shaders/shader.wgsl").to_string();
    let reps = env_usize("RUSTROOM_BENCH_REPS", 15);

    // (label, adjustments, patches applied to the shader source)
    let default_edit = serde_json::json!({ "exposure": 0.3, "contrast": 12.0, "highlights": -25.0, "shadows": 20.0 });
    let zero_edit = serde_json::json!({});
    let ablations: Vec<(&str, Vec<(&str, &str)>)> = vec![
        ("full shader", vec![]),
        ("- noise reduction", vec![(
            "initial_linear_rgb = apply_noise_reduction(\n        initial_linear_rgb, absolute_coord_i,\n        t_luma_nr, t_color_nr, scale, is_raw\n    );",
            "",
        )]),
        ("- white balance", vec![("composite_rgb_linear = apply_white_balance(composite_rgb_linear, t_temperature, t_tint);", "")]),
        ("- filmic exposure", vec![("composite_rgb_linear = apply_filmic_exposure(composite_rgb_linear, t_brightness);", "")]),
        ("- tonal + highlights", vec![
            ("composite_rgb_linear = apply_tonal_adjustments(composite_rgb_linear, tonal_blurred, is_raw, t_contrast, t_shadows, t_whites, t_blacks);", ""),
            ("composite_rgb_linear = apply_highlights_adjustment(composite_rgb_linear, tonal_blurred, is_raw, t_highlights);", ""),
        ]),
        ("- color calibration", vec![("composite_rgb_linear = apply_color_calibration(composite_rgb_linear, adjustments.global.color_calibration);", "")]),
        ("- HSL panel", vec![("if (hsl_magnitude > 0.0001) {", "if (false) {")]),
        ("- hue shift", vec![("composite_rgb_linear = apply_hue_shift(composite_rgb_linear, t_hue);", "")]),
        ("- creative color (sat/vib)", vec![("composite_rgb_linear = apply_creative_color(composite_rgb_linear, t_saturation, t_vibrance);", "")]),
        ("- centre tonal/color", vec![("composite_rgb_linear = apply_centre_tonal_and_color(composite_rgb_linear, adjustments.global.centre, absolute_coord_i);", "")]),
        ("- color grading", vec![(
            "    composite_rgb_linear = apply_color_grading(\n        composite_rgb_linear,\n        adjustments.global.color_grading_shadows,\n        adjustments.global.color_grading_midtones,\n        adjustments.global.color_grading_highlights,\n        adjustments.global.color_grading_global,\n        adjustments.global.color_grading_blending,\n        adjustments.global.color_grading_balance\n    );",
            "",
        )]),
        ("- curves", vec![(
            "if (!curves_identity) {",
            "if (false) {",
        )]),
        ("- dither", vec![("final_rgb += dither(id.xy) * dither_amount;", "")]),
    ];

    println!("\n=== Main shader ablation @ {}x{} on {} ({} reps, median ms, display path) ===", w, h, gpu_name, reps);
    let mut baseline_default = 0.0;
    for (label, patches) in &ablations {
        let mut src = base_src.clone();
        let mut ok = true;
        for (find, repl) in patches {
            if !src.contains(find) {
                println!("{:<32} PATCH NOT FOUND: {:.60}", label, find);
                ok = false;
                break;
            }
            src = src.replacen(find, repl, 1);
        }
        if !ok {
            continue;
        }
        *crate::gpu_processing::MAIN_SHADER_OVERRIDE.lock().unwrap() = Some(src);
        let p = GpuProcessor::new(ctx.clone(), padded(w), padded(h), true).expect("processor");
        let mut row = Vec::new();
        for adj in [&zero_edit, &default_edit] {
            render_display(&ctx, &p, &view, w, h, adj, None, None); // warmup / pipeline compile
            let (samples, _) = bench(reps, || render_display(&ctx, &p, &view, w, h, adj, None, None));
            row.push(stats(&samples).0);
        }
        if label == &"full shader" {
            baseline_default = row[1];
        }
        println!(
            "{:<32} zero-edit {:>7.2}   default-edit {:>7.2}   saving vs full {:>6.2}",
            label, row[0], row[1], baseline_default - row[1]
        );
        drop(p);
        gpu_wait(&ctx);
    }
    *crate::gpu_processing::MAIN_SHADER_OVERRIDE.lock().unwrap() = None;
}
