name: 'Release: Build & Package App'

on:
  release:
    types: [created]

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        # Windows and macOS only (Apple Silicon + Intel).
        include:
          - platform: 'windows-latest'
            args: '--bundles nsis'
            target: ''
            asset-prefix: '01'
          - platform: 'macos-14'
            target: aarch64-apple-darwin
            asset-prefix: '02'
          - platform: 'macos-15-intel'
            target: x86_64-apple-darwin
            asset-prefix: '02'
    uses: ./.github/workflows/build.yml
    with:
      release-id: ${{ github.event.release.id }}
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      asset-name-pattern: '[name]_v[version]_[platform]_[arch][ext]'
      asset-prefix: ${{ matrix.asset-prefix }}
      mobile: ${{ matrix.mobile }}
    secrets: inherit
    permissions:
      contents: write
